/**
 * Shell completion script generators for openapi2cli.
 *
 * Each function returns a string that can be sourced by the user's shell.
 * Dynamic operation completion (after `run --oas <spec>`) is handled by
 * calling back into the hidden `__completions` subcommand.
 */

const RUN_FLAGS = '--oas --bearer --api-key --api-key-header --basic --header --endpoint --help';
const GENERATE_FLAGS = '--oas --name --output --overwrite --help';
const TOP_COMMANDS = 'generate run completion help';
const COMPLETION_SHELLS = 'bash zsh fish';

// ─── Bash ─────────────────────────────────────────────────────────────────────

export function generateBashCompletion(): string {
  return [
    '# bash completion for openapi2cli',
    '# Source this file or add the following line to ~/.bashrc / ~/.bash_profile:',
    '#   eval "$(openapi2cli completion bash)"',
    '',
    '_openapi2cli() {',
    '  local cur prev words cword',
    '  _init_completion 2>/dev/null || {',
    '    COMPREPLY=()',
    '    cur="${COMP_WORDS[COMP_CWORD]}"',
    '    prev="${COMP_WORDS[COMP_CWORD-1]}"',
    '    words=("${COMP_WORDS[@]}")',
    '    cword=$COMP_CWORD',
    '  }',
    '',
    '  # Find the subcommand (first non-flag word after "openapi2cli")',
    '  local subcmd=""',
    '  local oas_path=""',
    '  local group=""',
    '  local i',
    '  for ((i=1; i<cword; i++)); do',
    '    case "${words[i]}" in',
    '      --oas) oas_path="${words[i+1]:-}"; ((i++)) ;;',
    '      generate|run|completion) subcmd="${words[i]}" ;;',
    '      --*) ;;  # skip other flags',
    '      *) [[ -n "$subcmd" && -z "$group" ]] && group="${words[i]}" ;;',
    '    esac',
    '  done',
    '',
    '  case "$prev" in',
    '    --oas|--output)',
    '      COMPREPLY=($(compgen -f -- "$cur"))',
    '      return ;;',
    '    --format)',
    '      COMPREPLY=($(compgen -W "json yaml table" -- "$cur"))',
    '      return ;;',
    '    --api-key-header)',
    '      COMPREPLY=($(compgen -W "X-Api-Key Authorization X-Token" -- "$cur"))',
    '      return ;;',
    '    completion)',
    `      COMPREPLY=($(compgen -W "${COMPLETION_SHELLS}" -- "$cur"))`,
    '      return ;;',
    '  esac',
    '',
    '  case "$subcmd" in',
    '    "")',
    `      COMPREPLY=($(compgen -W "${TOP_COMMANDS}" -- "$cur"))`,
    '      ;;',
    '    generate)',
    `      COMPREPLY=($(compgen -W "${GENERATE_FLAGS}" -- "$cur"))`,
    '      ;;',
    '    run)',
    '      if [[ -n "$oas_path" && -n "$group" ]]; then',
    '        # Complete operation names within the group',
    '        local ops',
    '        ops=$(openapi2cli __completions --oas "$oas_path" --group "$group" 2>/dev/null)',
    '        COMPREPLY=($(compgen -W "$ops" -- "$cur"))',
    '      elif [[ -n "$oas_path" && "$cur" != -* ]]; then',
    '        # Complete group names',
    '        local groups',
    '        groups=$(openapi2cli __completions --oas "$oas_path" 2>/dev/null)',
    '        COMPREPLY=($(compgen -W "$groups" -- "$cur"))',
    '      else',
    `        COMPREPLY=($(compgen -W "${RUN_FLAGS}" -- "$cur"))`,
    '      fi',
    '      ;;',
    '  esac',
    '}',
    '',
    'complete -F _openapi2cli openapi2cli',
    '',
  ].join('\n');
}

// ─── Zsh ──────────────────────────────────────────────────────────────────────

export function generateZshCompletion(): string {
  return [
    '#compdef openapi2cli',
    '# zsh completion for openapi2cli',
    '# Source this file or add the following to ~/.zshrc:',
    '#   eval "$(openapi2cli completion zsh)"',
    '',
    '_openapi2cli() {',
    '  local state line',
    '  typeset -A opt_args',
    '',
    '  _arguments -C \\',
    "    '(-h --help)'{-h,--help}'[Show help]' \\",
    "    '(-V --version)'{-V,--version}'[Show version]' \\",
    "    '1: :->subcmd' \\",
    "    '*:: :->args'",
    '',
    '  case $state in',
    '    subcmd)',
    '      local -a cmds',
    '      cmds=(',
    "        'generate:Generate a Commander.js CLI project from an OpenAPI spec'",
    "        'run:Directly call an OpenAPI endpoint without generating code'",
    "        'completion:Output shell completion script'",
    "        'help:Display help'",
    '      )',
    "      _describe 'command' cmds",
    '      ;;',
    '    args)',
    '      case $line[1] in',
    '        generate)',
    '          _arguments \\',
    "            '--oas[Path or URL to the OpenAPI spec file]:spec:_files' \\",
    "            '--name[CLI executable name]:name' \\",
    "            '--output[Output directory]:dir:_files -/' \\",
    "            '--overwrite[Overwrite existing output directory]' \\",
    "            '(-h --help)'{-h,--help}'[Show help]'",
    '          ;;',
    '        run)',
    '          _arguments -C \\',
    "            '--oas[Path or URL to the OpenAPI spec file]:spec:_files' \\",
    "            '--bearer[Bearer token]:token' \\",
    "            '--api-key[API key value]:key' \\",
    "            '--api-key-header[API key header name]:header:(X-Api-Key Authorization X-Token)' \\",
    "            '--basic[HTTP Basic credentials (user\\:pass)]:credentials' \\",
    "            '--header[Extra HTTP header (Name\\: Value)]:header' \\",
    "            '--endpoint[Override base URL]:url' \\",
    "            '(-h --help)'{-h,--help}'[Show help]' \\",
    "            '1: :->group' \\",
    "            '2: :->operation' \\",
    "            '*:: :->op_args'",
    '',
    '          local oas_path="${opt_args[--oas]}"',
    '',
    '          case $state in',
    '            group)',
    '              if [[ -n "$oas_path" ]]; then',
    '                local -a groups',
    '                groups=($(openapi2cli __completions --oas "$oas_path" 2>/dev/null))',
    "                _describe 'command group' groups",
    '              fi',
    '              ;;',
    '            operation)',
    '              if [[ -n "$oas_path" && -n "$line[1]" ]]; then',
    '                local -a ops',
    '                ops=($(openapi2cli __completions --oas "$oas_path" --group "$line[1]" 2>/dev/null))',
    "                _describe 'operation' ops",
    '              fi',
    '              ;;',
    '            op_args)',
    '              _arguments \\',
    "                '--format[Output format]:fmt:(json yaml table)' \\",
    "                '--query[JMESPath expression]:expr' \\",
    "                '--all-pages[Auto-paginate]' \\",
    "                '--verbose[Log HTTP method and URL]'",
    '              ;;',
    '          esac',
    '          ;;',
    '        completion)',
    "          _arguments '1: :(bash zsh fish)'",
    '          ;;',
    '      esac',
    '      ;;',
    '  esac',
    '}',
    '',
    '_openapi2cli "$@"',
    '',
  ].join('\n');
}

// ─── Fish ─────────────────────────────────────────────────────────────────────

export function generateFishCompletion(): string {
  return [
    '# fish completion for openapi2cli',
    '# Save this file to: ~/.config/fish/completions/openapi2cli.fish',
    '# Or run: openapi2cli completion fish > ~/.config/fish/completions/openapi2cli.fish',
    '',
    '# Disable file completions for the main command',
    'complete -c openapi2cli -f',
    '',
    '# Top-level subcommands',
    "complete -c openapi2cli -n '__fish_use_subcommand' -a 'generate'  -d 'Generate a CLI project from an OpenAPI spec'",
    "complete -c openapi2cli -n '__fish_use_subcommand' -a 'run'       -d 'Call an OpenAPI endpoint directly'",
    "complete -c openapi2cli -n '__fish_use_subcommand' -a 'completion' -d 'Output shell completion script'",
    "complete -c openapi2cli -n '__fish_use_subcommand' -a 'help'      -d 'Display help'",
    '',
    '# generate flags',
    "complete -c openapi2cli -n '__fish_seen_subcommand_from generate' -l oas       -r -d 'Path or URL to the OpenAPI spec'",
    "complete -c openapi2cli -n '__fish_seen_subcommand_from generate' -l name      -r -d 'CLI executable name'",
    "complete -c openapi2cli -n '__fish_seen_subcommand_from generate' -l output    -r -d 'Output directory'",
    "complete -c openapi2cli -n '__fish_seen_subcommand_from generate' -l overwrite     -d 'Overwrite existing output'",
    '',
    '# run flags',
    "complete -c openapi2cli -n '__fish_seen_subcommand_from run' -l oas            -r -d 'Path or URL to the OpenAPI spec'",
    "complete -c openapi2cli -n '__fish_seen_subcommand_from run' -l bearer         -r -d 'Bearer token'",
    "complete -c openapi2cli -n '__fish_seen_subcommand_from run' -l api-key        -r -d 'API key value'",
    "complete -c openapi2cli -n '__fish_seen_subcommand_from run' -l api-key-header -r -d 'API key header name'",
    "complete -c openapi2cli -n '__fish_seen_subcommand_from run' -l basic          -r -d 'HTTP Basic credentials (user:pass)'",
    "complete -c openapi2cli -n '__fish_seen_subcommand_from run' -l header         -r -d 'Extra HTTP header (Name: Value)'",
    "complete -c openapi2cli -n '__fish_seen_subcommand_from run' -l endpoint       -r -d 'Override base URL'",
    "complete -c openapi2cli -n '__fish_seen_subcommand_from run' -l format         -r -d 'Output format' -a 'json yaml table'",
    "complete -c openapi2cli -n '__fish_seen_subcommand_from run' -l query          -r -d 'JMESPath expression'",
    "complete -c openapi2cli -n '__fish_seen_subcommand_from run' -l all-pages          -d 'Auto-paginate'",
    "complete -c openapi2cli -n '__fish_seen_subcommand_from run' -l verbose            -d 'Log HTTP method and URL'",
    '',
    '# completion shells',
    "complete -c openapi2cli -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish' -d 'Shell type'",
    '',
  ].join('\n');
}
